name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: iamHaneef
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=purple
            dist/github-contribution-grid-snake.gif

      - name: Slow down Snake animation
        run: |
          sudo chown -R "$(id -u):$(id -g)" dist
          sed -i 's/29100ms/45000ms/g' dist/github-contribution-grid-snake-dark.svg
          sed -i 's/29100ms/45000ms/g' dist/github-contribution-grid-snake.svg

      - name: Publish Snake
        run: |
          cd dist

          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout --orphan output
          git add .
          git commit -m "Update Snake contribution graph"

          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push --force origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
